[env]
platform = nordicnrf52
board = nicla_sense_me
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyACM0
lib_deps = 
    arduino-libraries/ArduinoBLE @ ^1.3.6
    arduino-libraries/Arduino_BHY2 @ ^1.0.8

[env:production]
build_src_filter = -<*> +<main.cpp>

[env:testingSteps]
build_src_filter = -<*> +<testSteps.cpp>

[env:testingBat]
build_src_filter = -<*> +<testBat.cpp>